### ISSUE TITLE
404 Not Found 

### ISSUE THREAD

**Issue by ohotto** [isarlab-department-engineering/ARDVO#1]
There is a 404 Not Found on the dataset download page http://sira.diei.unipg.it/supplementary/public/ARD-VO/
![image](https://github.com/isarlab-department-engineering/ARDVO/assets/47439228/27525185-0079-4600-b2ef-3f8e36eb7880)
```
Not Found
The requested URL was not found on this server.
---------------------------------------------------------------
Apache/2.4.29 (Ubuntu) Server at sira.diei.unipg.it Port 80
```

**Comment by alberto1995** [comment]
Thanks for reporting this issue, we updated the link in the README.

This is the correct link: http://sira.diei.unipg.it/supplementary/public/Datasets/ARD-VO/
